name: Deploy to WP Engine (Staging & Production)

on:
  push:
    branches: [ "staging", "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-wpe-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List repo files (sanity check)
        run: |
          ls -la
          ls -la wp-content/themes/amaa-tmr || true
          ls -la wp-content/plugins/supabase-bridge || true

      # Upload local 'wp-content/themes/amaa-tmr' INTO 'sites/marketrepstg/wp-content/themes'
      - name: Deploy Theme to WPE Staging
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.STAGING_SFTP_HOST }}       # marketrepstg.sftp.wpengine.com
          username: ${{ secrets.STAGING_SFTP_USER }}     # e.g., marketrepstg-admin
          password: ${{ secrets.STAGING_SFTP_PASS }}
          port: 2222
          local_path: "wp-content/themes/amaa-tmr"
          remote_path: "sites/marketrepstg/wp-content/themes"
          sftp_only: true
          delete_remote_files: false
          sftpArgs: "-4 -o StrictHostKeyChecking=no"

      # Optional plugin deploy (only runs if folder exists)
      - name: Deploy Plugin to WPE Staging
        if: ${{ hashFiles('wp-content/plugins/supabase-bridge/**') != '' }}
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.STAGING_SFTP_HOST }}
          username: ${{ secrets.STAGING_SFTP_USER }}
          password: ${{ secrets.STAGING_SFTP_PASS }}
          port: 2222
          local_path: "wp-content/plugins/supabase-bridge"
          remote_path: "sites/marketrepstg/wp-content/plugins"
          sftp_only: true
          delete_remote_files: false
          sftpArgs: "-4 -o StrictHostKeyChecking=no"

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List repo files (sanity check)
        run: |
          ls -la
          ls -la wp-content/themes/amaa-tmr || true
          ls -la wp-content/plugins/supabase-bridge || true

      # Upload local 'wp-content/themes/amaa-tmr' INTO 'sites/thereport/wp-content/themes'
      - name: Deploy Theme to WPE Production
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.PROD_SFTP_HOST }}       # thereport.sftp.wpengine.com
          username: ${{ secrets.PROD_SFTP_USER }}     # thereport-admin
          password: ${{ secrets.PROD_SFTP_PASS }}
          port: 2222
          local_path: "wp-content/themes/amaa-tmr"
          remote_path: "sites/thereport/wp-content/themes"
          sftp_only: true
          delete_remote_files: false
          sftpArgs: "-4 -o StrictHostKeyChecking=no"

      # Optional plugin deploy (only runs if folder exists)
      - name: Deploy Plugin to WPE Production
        if: ${{ hashFiles('wp-content/plugins/supabase-bridge/**') != '' }}
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.PROD_SFTP_HOST }}
          username: ${{ secrets.PROD_SFTP_USER }}
          password: ${{ secrets.PROD_SFTP_PASS }}
          port: 2222
          local_path: "wp-content/plugins/supabase-bridge"
          remote_path: "sites/thereport/wp-content/plugins"
          sftp_only: true
          delete_remote_files: false
          sftpArgs: "-4 -o StrictHostKeyChecking=no"
